### ISSUE TITLE
댓글에서 Html 렌더링 되는 텍스트와 렌더링 되지 않는 텍스트의 크기와 스타일이 다름.

### ISSUE THREAD

**Issue by skykhs3** [sparcs-kaist/new-ara-app#95]
## Description 
댓글에서 Html 렌더링 되는 텍스트와 렌더링 되지 않는 텍스트의 크기와 스타일이 다름.

## To Reproduce
dev 자유 게시판의 '댓글 글씨체 확인' 게시물을 확인하시면 차이점을 더욱 잘 알 수 있습니다.

## Expected behavior
댓글에서 Html 렌더링 되는 텍스트와 렌더링 되지 않는 텍스트의 크기와 스타일이 같도록 지정.

## Screenshot
![Screenshot_20240218-230436](https://github.com/sparcs-kaist/new-ara-app/assets/5186472/960cac55-7069-4d7b-8da7-1f191d917ea9)
ots

## Development Environment
 - OS: macOS

## Test Environment
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - App Version: origin/fix/prevent-lt-gt(cb02a7603ec7a1e1d7c8e36e9ca845d9239d6751)

**Comment by skykhs3** [comment]
https://pub.dev/packages/flutter_html 이 라이브러리로 html을 렌더링 하지 않았던 이유가 뭔가요?

**Comment by sangohkim** [comment]
@skykhs3 PostViewPage 만들 당시에 고려대상 중 하나였으나
1. latest stable 버전(2.2.1)을 사용했을 때 dependency 문제 발생
2. dependency 문제가 없는 3.0.0버전이 있으나 아직 beta 버전인 상태
여서 사용하지 않고 웹뷰로 대체했었습니다.
그런데 웹뷰도 불안정한 부분이 있어서(특히 터지는 부분) beta 버전이라도 적용해보는 것이 어떨지 최근에 고민이 있습니다. 혹시 어떻게 생각하시나요?

**Comment by sangohkim** [comment]
2/19 월요일에 쭉 작업해보고 안되면 flutter_html 적용해보겠습니다.

**Comment by sangohkim** [comment]
위 PR에 의해 수정이 완료된 사안이라 이슈를 닫습니다.
